service: amazon-connect-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${file(config/env/${self:provider.stage}.yml):environmentVariables.region}
  stage: ${opt:stage, 'dev'}
  stackName: ${self:provider.stage}-${self:service}
  endpointType: REGIONAL

plugins:
- serverless-plugin-resource-tagging


package:
  individually: true

functions:
- ${file(config/function/integration.yml)}

resources:
- ${file(config/resources/hoursOfOperation.yml)}
- ${file(config/resources/queue.yml)}
- ${file(config/resources/routingProfile.yml)}
- ${file(config/resources/user.yml)}
- ${file(config/resources/lexBot.yml)}
- ${file(config/resources/botVersion.yml)}
- ${file(config/resources/contactFlow.yml)}


