environmentVariables:
  disconnect_time: 8
  idle_time: 2
  connect_instance_id: f6f46034-25c9-4bad-acad-3697484cb01a
  lambda_function: "aws-lambda-dev-lambdaFun"
  security_profile_id: 78ec6f05-a689-4556-8702-08acf910fbe6
  company_prefix: "digi"
  hoursofoperation_name: "serverlessHour"
  queue_name: "test_serverless_queue"
  lexbot_name: "test_serverless_lexbot"
  lexbot_alias_name: "testbot_alias"
  lexbot_alias_id: "TSTALIASID"
  routing_profile_id: "basic_serverless_routing"
  contact_flow_name: "serverless_abg_test_belusa_chatflow"
  region: us-east-1
  user_firstname: "Test"
  user_lastname: "Serverless"
  user_email_id: "serverlesstest@email.com"
  user_name: testServerless
