Resources:
  rHoursOfOperation:
    Type: "AWS::Connect::HoursOfOperation"
    Properties:
      InstanceArn: ${file(config/resources/references.yml):parameters.pConnectInstanceArn}
      Name: "${file(config/resources/references.yml):parameters.pHoursOfOprationName}"
      TimeZone: "America/New_York"
      Config:
        - Day: "SUNDAY"
          StartTime:
            Hours: 12
            Minutes: 0
          EndTime:
            Hours: 12
            Minutes: 0
        - Day: "MONDAY"
          StartTime:
            Hours: 12
            Minutes: 0
          EndTime:
            Hours: 12
            Minutes: 0
        - Day: "TUESDAY"
          StartTime:
            Hours: 12
            Minutes: 0
          EndTime:
            Hours: 12
            Minutes: 0
        - Day: "WEDNESDAY"
          StartTime:
            Hours: 12
            Minutes: 0
          EndTime:
            Hours: 12
            Minutes: 0
        - Day: "THURSDAY"
          StartTime:
            Hours: 12
            Minutes: 0
          EndTime:
            Hours: 12
            Minutes: 0
        - Day: "FRIDAY"
          StartTime:
            Hours: 12
            Minutes: 0
          EndTime:
            Hours: 12
            Minutes: 0
        - Day: "SATURDAY"
          StartTime:
            Hours: 12
            Minutes: 0
          EndTime:
            Hours: 12
            Minutes: 0 