Resources:
  rHoursOfOperation:
    Type: "AWS::Connect::HoursOfOperation"
    Properties:
      InstanceArn: !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${file(config/resources/references.yml):pConnectInstanceID}"
      Name: "${file(config/resources/references.yml):pCompany_profix}-${file(config/resources/references.yml):pHoursOfOprationName}"
      TimeZone: "America/New_York"
      Config:
      - Day: "SUNDAY"
        StartTime:
          Hours: 12
          Minutes: 0
        EndTime:
          Hours: 12
          Minutes: 0
      - Day: "MONDAY"
        StartTime:
          Hours: 12
          Minutes: 0
        EndTime:
          Hours: 12
          Minutes: 0
      - Day: "TUESDAY"
        StartTime:
          Hours: 12
          Minutes: 0
        EndTime:
          Hours: 12
          Minutes: 0
      - Day: "WEDNESDAY"
        StartTime:
          Hours: 12
          Minutes: 0
        EndTime:
          Hours: 12
          Minutes: 0
      - Day: "THURSDAY"
        StartTime:
          Hours: 12
          Minutes: 0
        EndTime:
          Hours: 12
          Minutes: 0
      - Day: "FRIDAY"
        StartTime:
          Hours: 12
          Minutes: 0
        EndTime:
          Hours: 12
          Minutes: 0
      - Day: "SATURDAY"
        StartTime:
          Hours: 12
          Minutes: 0
        EndTime:
          Hours: 12
          Minutes: 0
