Resources:
  rQueue:
    Type: "AWS::Connect::Queue"
    Properties:
      InstanceArn: ${file(config/resources/references.yml):parameters.pConnectInstanceArn}
      HoursOfOperationArn: !Ref rHoursOfOperation
      Name: "${file(config/resources/references.yml):parameters.pQueueName}"
      Description: "Queue for customer support"
      MaxContacts: 1