Resources:
  rQueue:
    Type: "AWS::Connect::Queue"
    Properties:
      InstanceArn: arn:aws:connect:us-east-1:767252029631:instance/f6f46034-25c9-4bad-acad-3697484cb01a
      HoursOfOperationArn: !Ref rHoursOfOperation
      Name: "test Serverless Queue"
      Description: "Queue for customer support"
      MaxContacts: 1