Resources:
  rRoutingProfile:
    Type: "AWS::Connect::RoutingProfile"
    Properties:
      InstanceArn: ${file(config/resources/references.yml):parameters.pConnectInstanceArn}
      Name: "${file(config/resources/references.yml):parameters.pRoutingProfileName}"
      Description: "Basic Routing Profile"
      DefaultOutboundQueueArn: !Ref rQueue
      MediaConcurrencies:
        - Channel: VOICE
          Concurrency: 1
        - Channel: CHAT
          Concurrency: 2
      QueueConfigs:
        - Delay: 0
          Priority: 1
          QueueReference:
            Channel: VOICE
            QueueArn: !Ref rQueue
        - Delay: 0
          Priority: 1
          QueueReference:
            Channel: CHAT
            QueueArn: !Ref rQueue
