Resources:
  rRoutingProfile:
    Type: "AWS::Connect::RoutingProfile"
    Properties:
      InstanceArn: !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${file(config/resources/references.yml):pConnectInstanceID}"
      Name: "${file(config/resources/references.yml):pCompany_profix}_${file(config/resources/references.yml):pRoutingProfileName}"
      Description: "Basic Routing Profile"
      DefaultOutboundQueueArn: !Ref rQueue
      MediaConcurrencies:
      - Channel: VOICE
        Concurrency: 1
      - Channel: CHAT
        Concurrency: 2
      QueueConfigs:
      - Delay: 0
        Priority: 1
        QueueReference:
          Channel: VOICE
          QueueArn: !Ref rQueue
      - Delay: 0
        Priority: 1
        QueueReference:
          Channel: CHAT
          QueueArn: !Ref rQueue
