Resources:
  rUser:
    Type: "AWS::Connect::User"
    Properties:
      IdentityInfo:
        FirstName: ${file(config/resources/references.yml):pUserFirstName}
        LastName: ${file(config/resources/references.yml):PUserLastName}
        Email: '${file(config/resources/references.yml):pUserEmailID}'
      PhoneConfig:
        PhoneType: SOFT_PHONE
      Username: ${file(config/resources/references.yml):pUserName}
      Password: ${param:pUserPassword}
      InstanceArn: !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${file(config/resources/references.yml):pConnectInstanceID}"
      RoutingProfileArn: !Ref rRoutingProfile
      SecurityProfileArns:
      - !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${file(config/resources/references.yml):pConnectInstanceID}/security-profile/${file(config/resources/references.yml):pSecurityProfileID}"
