Resources:
  rUser:
    Type: "AWS::Connect::User"
    Properties:
      IdentityInfo:
        FirstName: Test
        LastName: Serverless
        Email: 'serverlesstest@email.com'
      PhoneConfig: 
        PhoneType: SOFT_PHONE
      Username: testServerless
      Password: testServerless@123
      InstanceArn: ${file(config/resources/references.yml):parameters.pConnectInstanceArn}
      RoutingProfileArn: !Ref rRoutingProfile
      SecurityProfileArns: [arn:aws:connect:us-east-1:767252029631:instance/f6f46034-25c9-4bad-acad-3697484cb01a/security-profile/78ec6f05-a689-4556-8702-08acf910fbe6]
