Resources:
  rUser:
    Type: "AWS::Connect::User"
    Properties:
      IdentityInfo:
        FirstName: ${file(config/env/${self:provider.stage}.yml):environmentVariables.user_firstname}
        LastName: ${file(config/env/${self:provider.stage}.yml):environmentVariables.user_lastname}
        Email: '${file(config/env/${self:provider.stage}.yml):environmentVariables.user_email_id}'
      PhoneConfig:
        PhoneType: SOFT_PHONE
      Username: ${file(config/env/${self:provider.stage}.yml):environmentVariables.user_name}
      Password: ${param:pUserPassword}
      InstanceArn: !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${file(config/env/${self:provider.stage}.yml):environmentVariables.connect_instance_id}"
      RoutingProfileArn: !Ref rRoutingProfile
      SecurityProfileArns:
      - !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${file(config/env/${self:provider.stage}.yml):environmentVariables.connect_instance_id}/security-profile/${file(config/env/${self:provider.stage}.yml):environmentVariables.security_profile_id}"
